//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWC.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishItem
    {
        public DishItem()
        {
            this.IngredientItems = new HashSet<IngredientItem>();
        }
    
        public int Id { get; set; }
        public int ChefID { get; set; }
        public int DishID { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
        public string QRCode { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> CookingTime { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual Chef Chef { get; set; }
        public virtual Dish Dish { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual ICollection<IngredientItem> IngredientItems { get; set; }
    }
}
