//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWC.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.DishMenus = new HashSet<DishMenu>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.DishItems = new HashSet<DishItem>();
            this.Tags = new HashSet<Tag>();
            this.Ingredients = new HashSet<Ingredient>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int CategoryID { get; set; }
        public int ChefID { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
        public string CookingGuide { get; set; }
        public double Rate { get; set; }
        public bool IsAvailable { get; set; }
        public int NumberOfRate { get; set; }
        public int NumOfOrderQua1 { get; set; }
        public int NumOfOrderQua2 { get; set; }
        public int NumOfOrderQua3 { get; set; }
        public int NumOfOrderQua4 { get; set; }
        public int Year { get; set; }
    
        public virtual Chef Chef { get; set; }
        public virtual DishCategory DishCategory { get; set; }
        public virtual ICollection<DishMenu> DishMenus { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<DishItem> DishItems { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}
