//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWC.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientDishItem
    {
        public int DishItemID { get; set; }
        public int IngredientItemID { get; set; }
        public System.DateTime SupplyDate { get; set; }
    
        public virtual DishItem DishItem { get; set; }
        public virtual IngredientItem IngredientItem { get; set; }
    }
}
