//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWC.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.IngredientItems = new HashSet<IngredientItem>();
            this.Dishes = new HashSet<Dish>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Category { get; set; }
        public string ImageUrl { get; set; }
        public bool IsTracibility { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual IngredientCategory IngredientCategory { get; set; }
        public virtual ICollection<IngredientItem> IngredientItems { get; set; }
        public virtual ICollection<Dish> Dishes { get; set; }
    }
}
