//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWC.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.DishMenus = new HashSet<DishMenu>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public bool IsAvailable { get; set; }
        public System.DateTime ClosedTimeSession { get; set; }
    
        public virtual ICollection<DishMenu> DishMenus { get; set; }
    }
}
