//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWC.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientItem
    {
        public IngredientItem()
        {
            this.DishItems = new HashSet<DishItem>();
        }
    
        public int Id { get; set; }
        public int SupplierID { get; set; }
        public int IngredientID { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsDefaultSupplier { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<DishItem> DishItems { get; set; }
    }
}
