//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Bills = new HashSet<Bill>();
            this.FAQs = new HashSet<FAQ>();
            this.Dishes = new HashSet<Dish>();
            this.FAQs1 = new HashSet<FAQ>();
        }
    
        public int CustomerId { get; set; }
        public string ImageURL { get; set; }
        public int CustomerType { get; set; }
        public int TotalOrderValue { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<FAQ> FAQs { get; set; }
        public virtual ICollection<Dish> Dishes { get; set; }
        public virtual ICollection<FAQ> FAQs1 { get; set; }
    }
}
