//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishOrderSummary
    {
        public int DishId { get; set; }
        public int NumOfOrderQua1 { get; set; }
        public int NumOfOrderQua2 { get; set; }
        public int NumOfOrderQua3 { get; set; }
        public int NumOfOrderQua4 { get; set; }
        public int Year { get; set; }
    
        public virtual Dish Dish { get; set; }
    }
}
