//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishMenu
    {
        public int DishID { get; set; }
        public int MenuID { get; set; }
        public int DishPrice { get; set; }
        public int Quota { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
