//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public FAQ()
        {
            this.FAQComments = new HashSet<FAQComment>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int FAQId { get; set; }
        public int ChefId { get; set; }
        public int UserId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public int NumOfLike { get; set; }
        public int Status { get; set; }
    
        public virtual Chef Chef { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<FAQComment> FAQComments { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
