//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQComment
    {
        public FAQComment()
        {
            this.FAQComment1 = new HashSet<FAQComment>();
        }
    
        public int FAQCommentId { get; set; }
        public int FAQId { get; set; }
        public int UserId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ParentComment { get; set; }
    
        public virtual FAQ FAQ { get; set; }
        public virtual ICollection<FAQComment> FAQComment1 { get; set; }
        public virtual FAQComment FAQComment2 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
