//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.ChefSkills = new HashSet<ChefSkill>();
        }
    
        public int Id { get; set; }
        public string SkillName { get; set; }
    
        public virtual ICollection<ChefSkill> ChefSkills { get; set; }
    }
}
